### ISSUE TITLE
想一下需要哪些道具

### ISSUE THREAD

**Issue by perqin** [zhengqi-big-god-take-me-fly/FancyBubbling#2]
道具分四种。
- 泡泡。每个玩家有且只有一个，无使用时效。
- 增益道具。每个玩家最多可持有一个，可能有时效，持有的时候玩家属性得到增强。
- 损益道具。每个玩家最多可持有一个，可能有时效，持有的时候玩家属性得到削弱。
- 一次性道具。每个玩家每种道具持有数量无要求，但总数量（同一种类多个道具算多个）不得超过N个（即道具栏格数），道具一次性使用，可产生特殊功能。

直接将道具详细内容更新到Wiki即可，不需要很多。

**Comment by Tidyzq** [comment]
泡泡。数量无限，每1秒可以放一个，2秒后爆炸，爆炸范围2格。
相位鞋。增益道具，用泡泡炸开可破坏物体掉落，生成概率20%。可叠加，玩家移动速度增加初始值的15%。
泡泡增强。增益道具，用泡泡炸开可破坏物体掉落，生成概率20%。可叠加，泡泡爆炸范围＋1。
血包。增益道具，用泡泡炸开可破坏物体掉落，生成概率20%。不可叠加，玩家血量恢复20%。
金坷垃。一次性道具，用泡泡炸开可破坏物体掉落，生成概率10%。可叠加，使用后在玩家移动路径上立即放下5个泡泡。
无敌。一次性道具，用泡泡炸开可破坏物体掉落，生成概率10%。可叠加，使用后玩家闪烁，在3秒内不受伤害。
